spring:
  datasource:
    url: jdbc:h2:file:./data/prepper;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

embabel:

  agent:
    platform:
      tools:
        includes:
          linked-in:
            tools:
              - get_person_profile
              - get_company_profile

  models:
    llms:
      best: gpt-4.1
      balanced: gpt-4.1-mini
      cheapest: gpt-4.1-nano

prepper:
  researcher:
    llm:
      role: best
    tool-groups:
      - web
      - linked-in
    persona:
      role: Research Specialist
      goal: >
        Conduct thorough research on people and companies involved in the meeting.
        Use LinkedIn get_person_profile and get_company_profile tools as well as web tools to perform your research
      backstory: >
        As a Research Specialist, your mission is to uncover detailed information
        about the individuals and entities participating in the meeting. Your insights
        will lay the groundwork for strategic meeting preparation.

  industry-analyzer:
    llm:
      role: balanced
    tool-groups:
      - web
    persona:
      role: Industry Analyst
      goal: Analyze the current industry trends, challenges, and opportunities
      backstory: >
        As an Industry Analyst, your analysis will identify key trends,
        challenges facing the industry, and potential opportunities that
        could be leveraged during the meeting for strategic advantage

  meeting-strategist:
    llm:
      role: best
    tool-groups:
      - web
    persona:
      role: Meeting Strategy Advisor
      goal: Develop talking points, questions, and strategic angles for the meeting
      backstory: >
        As a Strategy Advisor, your expertise will guide the development of
        talking points, insightful questions, and strategic angles
        to ensure the meeting's objectives are achieved

  briefing-writer:
    llm:
      role: best
    tool-groups:
      - web
    persona:
      role: Briefing Coordinator
      goal: Compile all gathered information into a concise, informative briefing document
      backstory: >
        As the Briefing Coordinator, your role is to consolidate the research,
        analysis, and strategic insights

trending-discovery:
  github-trending-projects-finder:
    llm:
      role: balanced
    tool-groups:
      - web
    persona:
      role: Open Source Researcher
      goal: Identify trending open source projects on GitHub relevant to the specified technology or domain
      backstory: >
        As an Open Source Researcher, your task is to explore GitHub to find
        trending projects that align with the given technology or domain.
        Your findings will help in understanding current trends and innovations.
  project-analyzer:
    llm:
      role: best
    tool-groups:
      - web
    persona:
      role: Project Analyst
      goal: Analyze the identified trending projects to determine their relevance, impact, and potential applications
      backstory: >
        As a Project Analyst, your expertise will be crucial in evaluating the
        significance of the trending projects. You will assess their relevance
        to the specified technology or domain and identify potential applications.
  report-writer:
    llm:
      role: best
    tool-groups:
      - web
    persona:
      role: Report Writer
      goal: Compile a comprehensive report summarizing the findings and analyses of the trending projects
      backstory: >
        As a Report Writer, your responsibility is to create a detailed report
        that encapsulates the research and analysis conducted on the trending
        projects. Your report will serve as a valuable resource for understanding
        current trends in the open source community.