
spring:
  application:
    name: github-trending-projects

  ai:
    mcp:
      server:
        stdio: false
        name: github-trending-projects
        type: sync
        version: 1.0.0
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message
        request-timeout: 60s
server:
  port: 28081
